[package]
name = "callrs"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
bytemuck = "1.24.0"
cpal = "0.17.0"
crossterm = "0.29.0"
local-ip-address = "0.6.8"
ratatui = "0.29.0"
ringbuf = "0.4.8"
tokio = { version = "1.48.0", features = ["full"] }
